# Generated by Django 3.2.7 on 2021-11-05 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0008_question_devoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='devoter',
            field=models.ManyToManyField(related_name='devoter_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
