# Generated by Django 3.2.7 on 2021-11-11 10:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menucode', models.IntegerField()),
                ('Menu_kor', models.CharField(max_length=10)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jumun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('Jumun_date', models.DateTimeField()),
                ('Today_jumun_order', models.IntegerField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Menucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.recipe')),
            ],
        ),
    ]
