# Generated by Django 3.2.7 on 2021-11-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_alter_jumun_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jumun',
            old_name='Count',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='jumun',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='jumun',
            old_name='Jumun_date',
            new_name='jumun_date',
        ),
        migrations.RenameField(
            model_name='jumun',
            old_name='Menucode',
            new_name='menucode',
        ),
        migrations.RenameField(
            model_name='jumun',
            old_name='Today_jumun_order',
            new_name='today_jumun_order',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Menu_kor',
            new_name='menu_name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Menucode',
            new_name='menucode',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Price',
            new_name='price',
        ),
    ]
