# Generated by Django 3.2.7 on 2021-11-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_auto_20211111_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='menucode',
            field=models.CharField(max_length=5),
        ),
    ]
